![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)
print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


In [10]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [11]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [16]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [19]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [23]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [24]:
x == "Loro"

array([ True, False, False,  True, False])

In [25]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [26]:
print(np.where(x== "Loro")[0])

[0 3]


In [27]:
print(np.where(x == "Loro")[0])

[0 3]


In [28]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [29]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [30]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [31]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [32]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [33]:
import numpy as np

# Crear un array de 10 ceros
array = np.zeros(10,dtype=int)
array

memoria_ocupada = array.nbytes
print(memoria_ocupada)

array[3] = 1


array


80


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [34]:
import numpy as np

vector_np = np.arange(10, 50)
print(vector_np)

vector_np_invertido = np.flip(vector_np)

print(vector_np_invertido)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [35]:
import numpy as np


def valores_no_cero(vector):
    
    return vector[np.nonzero(vector)]

vector_ = np.array([1, 2, 0, 0, 4, 0])
#zeros2 = np.nonzero(vector_ejemplo)
#print(zeros2)

valores = valores_no_cero(vector_)

print(valores)



[1 2 4]


In [40]:
j = np.array([1, 2, 0, 0, 4, 0])
print(np.where(j != 0)[0])

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [36]:

matriz_aleatoria = np.random.randint(100, size = (10,10))
print(matriz_aleatoria)

valor_minimo = round(np.min(matriz_aleatoria),3)
valor_maximo = round(np.max(matriz_aleatoria),3)


valor_minimo, valor_maximo


[[ 1 23 84 52 93 53  3 79 86 51]
 [19 66 54 72  5 17 40 99 80 19]
 [26  6 36  4 68  7 68 43 99 23]
 [84 79 50  5 58 56 59 61 27  0]
 [72 61 67 13 61 93  1 20 54 95]
 [37 63 99 24 99 92 94 18 89 90]
 [ 1 66 38 22 78 54 83 36  7  4]
 [ 6 93 57 57 67 58 64 42  6 27]
 [97 12 35 80 81  9  2 34 82 82]
 [77 59 59 45 32 50 98 92 26 62]]


(np.int32(0), np.int32(99))

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [37]:
vector_aleatorio = np.random.rand(30)
print(vector_aleatorio)

media_vector = np.mean(vector_aleatorio)

media_vector


[0.15028161 0.74084429 0.43491321 0.38672753 0.22853115 0.89955805
 0.94500014 0.62673078 0.59724125 0.06329026 0.99002992 0.35781898
 0.05021014 0.62986985 0.16058454 0.52861799 0.89417282 0.05526788
 0.24700904 0.77160896 0.48398797 0.6274635  0.89351592 0.7836924
 0.08950894 0.14234516 0.38072479 0.23509921 0.33604119 0.77087519]


np.float64(0.4833854219653581)

## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [43]:
matriz = np.random.randint(20 , size=(5, 5))
print(matriz)

media = np.mean(matriz)
print(media)
desviacion_estandar = np.std(matriz)

matriz_normalizada = (matriz - media) / desviacion_estandar

matriz_normalizada


[[12  5 19  4 11]
 [ 8 16 13 18  2]
 [ 6 11  5  6  8]
 [ 8  6  9  6 16]
 [ 8  4  1  3 17]]
8.88


array([[ 0.61346998, -0.76290498,  1.98984493, -0.95952997,  0.41684499],
       [-0.17302999,  1.39996995,  0.81009497,  1.79321994, -1.35277996],
       [-0.56627998,  0.41684499, -0.76290498, -0.56627998, -0.17302999],
       [-0.17302999, -0.56627998,  0.023595  , -0.56627998,  1.39996995],
       [-0.17302999, -0.95952997, -1.54940495, -1.15615496,  1.59659495]])

## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [44]:
import numpy as np

secuencia = np.arange(11)

array_modificado = secuencia.copy()
array_modificado[(array_modificado >= 3) & (array_modificado <= 8)] = -1

array_negado = secuencia.copy()
array_negado[(array_negado >= 3) & (array_negado <= 8)] *= -1

# Imprimir resultados
print("Secuencia original:", secuencia)
print("Array modificado:", array_modificado)
print("Array negado:", array_negado)


Secuencia original: [ 0  1  2  3  4  5  6  7  8  9 10]
Array modificado: [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Array negado: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
